services:
  php:
    build:
      context: docker/php
    volumes:
      - ./:/var/www/:cached
    ports:
      - 80:8000
    depends_on:
      - mysql
      - node

  mysql:
    image: mysql:8.4
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=wordplate
    restart: always

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8180:80
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=password

  node:
    build:
      context: docker/node
    volumes:
      - ./:/var/www:cached
    ports:
      - 5173:5173

volumes:
  mysql_data:
